services:
  # React Client service
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    restart: always
    networks:
      - font-manager-network

  # PHP Server service
  server:
    build:
      context: ./server
    volumes:
      - ./server/uploads:/var/www/html/uploads
      - ./server/data:/var/www/html/data
      - ./server:/app
    ports:
      - "5000:5000"
    restart: always
    networks:
      - font-manager-network

# Networks to be created
networks:
  font-manager-network:
    driver: bridge
